version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1111111111
      MYSQL_DATABASE: koonnkt_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111111111
    ports:
      - "3307:3307"
    networks:
      - koonnkt_network

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/koonnkt_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1111111111
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - koonnkt_network

networks:
  koonnkt_network:
    driver: bridge
